### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by chornbe** [OpenFlutter/flutter_image_compress#73] opened 2019-07-19 11:35 UTC
Flutter v 1.8.1
Kotlin v 1.3.41
Android Studio v 3.4.2
Mac OS 10.14.5

What other info should I provide to help determine what's causing the following error...? Thanks

Running flutter build apk --release emits the following information:

admins-MBP:diary_app_flutter chris$ flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              0.9s
Resolving dependencies...                                           9.5s
Note: /Users/chris/development/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+1/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
e: /Users/chris/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.2/android/src/main/kotlin/com/example/flutterimagecompress/FlutterImageCompressPlugin.kt: (25, 76): Type mismatch: inferred type is Activity! but AppCompatActivity was expected
e: /Users/chris/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.2/android/src/main/kotlin/com/example/flutterimagecompress/FlutterImageCompressPlugin.kt: (26, 76): Type mismatch: inferred type is Activity! but AppCompatActivity was expected
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      82.4s
Gradle task assembleRelease failed with exit code 1

Here's the dependency list from my flutter project yaml file:
```
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  shared_preferences: 0.5.2+1
  connectivity: 0.4.3+1
  flutter_launcher_icons: "^0.7.0"
  package_info: ^0.4.0+3
  intl: ^0.15.8
  palette_generator: ^0.1.1
  uuid: ^2.0.1
  image_picker: ^0.4.10
  camera: ^0.4.2
  flutter_image_compress: ^0.6.2
  # image_gallery_saver: ^1.1.0

```

**Comment by CaiJingLong** [comment] 2019-07-20 06:46
I try create flutter project, and add the dependencies for the project.

Project repository is https://dev.azure.com/cjlspy/_git/flutter_try_use_library_1

And I  edit miniSdk version to 21 and run it in command-line:
```bash
flutter pub get
flutter build apk --release
```
Then, I get this log:

```bash
flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              1.2s
Resolving dependencies...                                           2.2s
注: /Users/caijinglong/.pub-cache/hosted/pub.flutter-io.cn/connectivity-0.4.3+1/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/caijinglong/.pub-cache/hosted/pub.flutter-io.cn/package_info-0.4.0+5/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
Calling mockable JAR artifact transform to create file: /Users/caijinglong/.gradle/caches/transforms-1/files-1.1/android.jar/ce8e87e89203692dec1a4eb30537b568/android.jar with input /Users/caijinglong/Library/Android/sdk/platforms/android-27/android.jar
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      52.5s
Built build/app/outputs/apk/release/app-release.apk (11.2MB).
```

I don't meet your problem, and I get an apk file.

**Comment by CaiJingLong** [comment] 2019-07-20 06:47
![image](https://user-images.githubusercontent.com/14145407/61575365-5588fe80-aafd-11e9-84a6-2de4c1f2ca30.png)

**Comment by CaiJingLong** [comment] 2019-07-24 08:14
I can't reproduce your build error.
I'll close it.
If you have a way to reproduce it (provide a repository in github), please reopen this issue.

**Closed** 2019-07-24 08:14 UTC
