### ISSUE TITLE
performance (isolate)

### ISSUE THREAD

**Issue by ashkryab** [OpenFlutter/flutter_image_compress#47] opened 2019-05-21 08:10 UTC
need a synchronous analogue of the function CompressAndGetFile, for works with isolations. What function would return the File not Future<File>

**Comment by CaiJingLong** [comment] 2019-05-21 09:00
I don't understand what you mean.

**Comment by ashkryab** [comment] 2019-05-21 11:40
isolation can return simple objects. Insulations cannot return Furure. To process the image in isolation using this library a method is needed that will return the file synchronously

**Comment by CaiJingLong** [comment] 2019-05-21 12:00
1. There is no way to convert async to sync. 
2. This library is based on native implementation. Thread pool and GCD are used natively. You don't need to use isolate of dart specifically and native plugin don't support isolate.

**Comment by CaiJingLong** [comment] 2019-06-25 05:31
I'll close the issue.  
Because native plugins cannot be called in isolate. This is not caused by the plugins themselves, but by flutter sdk.

**Closed by CaiJingLong** 2019-06-25 05:31 UTC
