### ISSUE TITLE
Support compressing from rawRGB

### ISSUE THREAD

**Issue by ianpark** [OpenFlutter/flutter_image_compress#91] opened 2019-10-05 22:27 UTC
### Feature
Support compressing from rawRGB

### Detail
To capture the current widget, I use `RenderRepaintBoundary` like below.
```
RenderRepaintBoundary boundary =
      ImagePanel.globalKey.currentContext.findRenderObject();
  ui.Image image = await boundary.toImage(pixelRatio: 3);
  ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
  Uint8List result = byteData.buffer.asUint8List();
```
However ` image.toByteData()` is super slow if it is called with `ImageByteFormat.png` but super fast with `ImageByteFormat.rawRgb`.

If `flutter_image_compress` supports compressing from rawRGB, it's going to solve this problem.

**Comment by CaiJingLong** [comment] 2019-10-08 01:36
Unable to process, raw is unprocessed raw data, similar to yuv data, which only contains color information, not even width and height.

**Comment by CaiJingLong** [comment] 2020-01-10 08:33
I'll close it, because in my opinion this is not a problem.

**Closed by CaiJingLong** 2020-01-10 08:33 UTC
Labels: enhancement, wontfix

**Comment by cmkweber** [comment] 2020-01-10 18:16
I can confirm with my tests there would be a major speed improvement if rawRgb was used.

**Comment by rivereed** [comment] 2022-01-31 16:10
+1 for the ability to pass in raw RGB[A} and produce an image. Easy to specify this (with whatever simplifications you want, like only support srgb and rgba byte order for now)
