### ISSUE TITLE
A obsoleted API Issue

### ISSUE THREAD

**Issue by yourlin** [OpenFlutter/flutter_image_compress#88] opened 2019-09-18 23:28 UTC
WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: flutter_image_compress

**Comment by CaiJingLong** [comment] 2019-09-19 01:20
This problem is a problem with gradle. 
The script inside the plugin has not called this method. 

And, I use the master version of flutter. The flutter build apk command does not show this warning, so it may be caused by the flutter version. So I think you can ignore it.

**Comment by CaiJingLong** [comment] 2020-01-10 08:31
Add next code to `android/gradle.properties`.
`android.debug.obsoleteApi=true`

![image](https://user-images.githubusercontent.com/14145407/72137856-8d933f00-33c6-11ea-9402-db89e299aef1.png)

The tip come from flutter sdk, no the library, So I'll close it.

**Closed by CaiJingLong** 2020-01-10 08:31 UTC
